import "dotenv/config";
import { getCharacterName, getUserNickname } from "./personality.js";

console.log(`╔══════════════════════════════════════════╗`);
console.log(`║       ${getCharacterName()} AI Agent           ║`);
console.log(`║   基于 永劫无间·蓝梦 角色设定             ║`);
console.log(`║   Powered by DeepSeek                    ║`);
console.log(`╚══════════════════════════════════════════╝`);
console.log("");
console.log("使用方式：");
console.log("");
console.log("  npm run chat      命令行聊天模式");
console.log("  npm run wechat    微信扫码接入（需要 ClawBot 插件）");
console.log("");
console.log("使用方式：");
console.log("");
console.log("  npm run chat      命令行聊天模式");
console.log("  npm run wechat    微信扫码接入（需要 ClawBot 插件）");
console.log("");
console.log(`她会叫你"${getUserNickname()}"~`);
console.log("");
console.log("✨ 微信模式特色：");
console.log("  - 5 分钟无对话自动发消息找你");
console.log("  - 早晚时段有特别的问候");
console.log("  - /ping 在线检测  /sleep 暂停主动消息  /wake 恢复");
console.log("");
console.log("首次使用：");
console.log("  1. 编辑 .env 确认 DEEPSEEK_API_KEY 已配置");
console.log("  2. npm install");
console.log("  3. npm run chat 或 npm run wechat");
