import "dotenv/config";
import { getCharacterName, getUserNickname } from "./personality.js";

console.log(`╔══════════════════════════════════════════╗`);
console.log(`║     ${getCharacterName()} AI Agent v2            ║`);
console.log(`║  基于 永劫无间·蓝梦 角色设定             ║`);
console.log(`║  Powered by DeepSeek                    ║`);
console.log(`╚══════════════════════════════════════════╝`);
console.log("");
console.log("使用方式：");
console.log("");
console.log("  npm run chat      命令行聊天模式");
console.log("  npm run wechat    微信扫码接入（本地终端）");
console.log("  npm run server    服务器模式（网页二维码 + 24h 在线）");
console.log("");
console.log(`她会叫你"${getUserNickname()}"~`);
console.log("");
console.log("✨ 新功能：");
console.log("  🧠 三层记忆系统（短期+摘要+事实）");
console.log("  🔍 联网搜索（自动查梗、查新闻、查天气）");
console.log("  💬 主动消息（/wake 开启）");
console.log("  🌐 服务器网页扫码（无需本地终端）");
console.log("");
console.log("首次使用：");
console.log("  1. 编辑 .env 确认 DEEPSEEK_API_KEY 已配置");
console.log("  2. npm install");
console.log("  3. npm run chat / npm run wechat / npm run server");
